export const APPROUTES = {
    LOGIN: "/login",
    SIGNUP: "/signup",
    HOME: "/",
    ABOUT: "/about",
    CONTACT: "/contact",
    SERVICES: "/services",
    SERVICE_DETAIL: "/services/:service",
    SERVICES_REDIRECT: "/services/gardening",
    CART: "/cart",
    WISHLIST: "/wishlist",
    SHIPPING: "/shipping",
    CHECKOUT: "/checkout",
    HELP_CENTER: "/help-center",
};
